"""empty message

Revision ID: 3b22d9d45265
Revises: a2a226e061ea
Create Date: 2022-02-26 05:47:48.347079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b22d9d45265'
down_revision = 'a2a226e061ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('guest_email', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'guest_email')
    # ### end Alembic commands ###
