"""empty message

Revision ID: 61185600552a
Revises: 4a2f8dbb548d
Create Date: 2022-02-25 22:45:10.368795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61185600552a'
down_revision = '4a2f8dbb548d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
