"""empty message

Revision ID: 65e730ce2d05
Revises: 6ed7295f0fe4
Create Date: 2022-03-02 03:07:02.208569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e730ce2d05'
down_revision = '6ed7295f0fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('email', sa.String(length=80), nullable=False))
    op.drop_column('guest', 'guest_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('guest_email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('guest', 'email')
    # ### end Alembic commands ###
