"""empty message

Revision ID: 6ed7295f0fe4
Revises: 3b22d9d45265
Create Date: 2022-03-01 00:26:43.651827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed7295f0fe4'
down_revision = '3b22d9d45265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Hash', sa.String(length=120), nullable=False),
    sa.Column('guest_email', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Hash')
    )
    op.create_table('guest_association',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('guest_id', 'permission_id')
    )
    op.drop_table('room')
    op.drop_table('token_association')
    op.drop_table('token')
    op.add_column('coordinator', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('coordinator', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('guest_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'event', 'guest', ['guest_id'], ['id'])
    op.add_column('permission', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('permission', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'permission', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_column('permission', 'updated_at')
    op.drop_column('permission', 'name')
    op.drop_column('permission', 'created_at')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'guest_id')
    op.drop_column('event', 'created_at')
    op.drop_column('coordinator', 'updated_at')
    op.drop_column('coordinator', 'created_at')
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('token_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('Hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('guest_email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_pkey'),
    sa.UniqueConstraint('Hash', name='token_Hash_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('token_association',
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='token_association_permission_id_fkey'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], name='token_association_token_id_fkey'),
    sa.PrimaryKeyConstraint('token_id', 'permission_id', name='token_association_pkey')
    )
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='room_event_id_fkey'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='room_permission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_pkey'),
    sa.UniqueConstraint('room_name', name='room_room_name_key')
    )
    op.drop_table('guest_association')
    op.drop_table('guest')
    # ### end Alembic commands ###
