"""empty message

Revision ID: 763fadc6d6ad
Revises: e72fb2988dab
Create Date: 2022-03-15 16:52:29.276564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '763fadc6d6ad'
down_revision = 'e72fb2988dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    op.drop_table('features_association')
    op.drop_constraint('permission_guest_name_key', 'permission', type_='unique')
    op.drop_column('permission', 'guest_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('guest_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('permission_guest_name_key', 'permission', ['guest_name'])
    op.create_table('features_association',
    sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('features_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['features_id'], ['features.id'], name='features_association_features_id_fkey'),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name='features_association_guest_id_fkey'),
    sa.PrimaryKeyConstraint('guest_id', 'features_id', name='features_association_pkey')
    )
    op.create_table('features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vip', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('valet', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dinner', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='features_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='features_pkey')
    )
    # ### end Alembic commands ###
