"""empty message

Revision ID: 77a5bc99d161
Revises: 65e730ce2d05
Create Date: 2022-03-02 23:03:09.312540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a5bc99d161'
down_revision = '65e730ce2d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinator', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coordinator', 'is_active')
    # ### end Alembic commands ###
