"""empty message

Revision ID: 7fd4224a743f
Revises: 9e2e5ea96749
Create Date: 2022-03-18 05:20:54.910909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd4224a743f'
down_revision = '9e2e5ea96749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest', 'image')
    # ### end Alembic commands ###
