"""empty message

Revision ID: 9a6a0ead4583
Revises: 728be4457244
Create Date: 2022-03-11 23:01:30.610764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6a0ead4583'
down_revision = '728be4457244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vip', sa.Boolean(), nullable=False),
    sa.Column('valet', sa.Boolean(), nullable=False),
    sa.Column('dinner', sa.Boolean(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features_association',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('features_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['features_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('guest_id', 'features_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features_association')
    op.drop_table('features')
    # ### end Alembic commands ###
