"""empty message

Revision ID: 9e2e5ea96749
Revises: 7755a237bf9d
Create Date: 2022-03-17 19:46:34.241292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2e5ea96749'
down_revision = '7755a237bf9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_guest_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'guest_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_guest_id_fkey', 'event', 'guest', ['guest_id'], ['id'])
    # ### end Alembic commands ###
