"""empty message

Revision ID: a64c346c1312
Revises: 77a5bc99d161
Create Date: 2022-03-05 01:44:19.258930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c346c1312'
down_revision = '77a5bc99d161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('guest_hash', sa.String(length=500), nullable=False))
    op.drop_constraint('guest_Hash_key', 'guest', type_='unique')
    op.create_unique_constraint(None, 'guest', ['guest_hash'])
    op.drop_column('guest', 'Hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('Hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'guest', type_='unique')
    op.create_unique_constraint('guest_Hash_key', 'guest', ['Hash'])
    op.drop_column('guest', 'guest_hash')
    # ### end Alembic commands ###
