"""empty message

Revision ID: e72fb2988dab
Revises: aff35df8c132
Create Date: 2022-03-14 11:44:28.191713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72fb2988dab'
down_revision = 'aff35df8c132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('guest_name', sa.String(length=120), nullable=False))
    op.drop_constraint('permission_name_key', 'permission', type_='unique')
    op.create_unique_constraint(None, 'permission', ['guest_name'])
    op.drop_column('permission', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permission', type_='unique')
    op.create_unique_constraint('permission_name_key', 'permission', ['name'])
    op.drop_column('permission', 'guest_name')
    # ### end Alembic commands ###
